### ISSUE TITLE
Vector of prepared statement parameters

### ISSUE THREAD

**Issue by tmayoff** [boostorg/mysql#142]
I'm trying to create a query builder that dynamically adds parameters to a the list of prepared statements (something I have working using the mariadbcppconnector) I'd like to do the same with this library, is there a way to pass parameters with a non-compile time known number of them

**Comment by anarthal** [comment]
Yes, you can. You need to use the iterator version of [`start_statement_execution`](https://www.boost.org/doc/libs/1_82_0/libs/mysql/doc/html/mysql/ref/boost__mysql__connection/start_statement_execution.html). Using this, you can pass any forward range of `field_view`s as parameters.

Right now, this forces you to use the [multi-function interface](https://www.boost.org/doc/libs/1_82_0/libs/mysql/doc/html/mysql/multi_function.html) - i.e., there is no `execute_statement` that takes an iterator pair and returns a `results`.

Example code:

```
// conn is a connection object, stmt is a statement object

// Obtain a collection containing the parameters of your statement as field_view's.
// field_view's are lightweight variant-like objects that can represent any MySQL type
std::vector<field_view> params { field_view(42), field_view("abc"), field_view(nullptr) };

// an execution_state is an object that holds info about an execute operation,
// and is the main interface to multi-function operations
execution_state st;

// start the operation. This sends the request to the server and reads the response, but not the rows
conn.start_statement_execution(stmt, params.begin(), params.end(), st);

// Read the rows
while (!st.complete())
{
    // Read a batch. This batch points into conn's buffers and is valid
    // until you perform any further network activity on conn
    rows_view row_batch = conn.read_some_rows(st);

    // Use the batch as required
}
```

There is no way to coalesce several `rows_views` into a single `results` object.

Boost 1.83 will include support for executing statements with iterator ranges and returning a `result` - the feature is available for preview in the develop branch. If it's something you're interested in, let me know and I'll provide more documentation on it.

Regards,
Ruben.

**Comment by tmayoff** [comment]
I would be interested in trying out what's in the develop branch, some more documentation would be great thanks!

**Comment by tmayoff** [comment]
I managed to find the documentation myself, and figure it out. Thanks for the help!

**Comment by anarthal** [comment]
As an additional note, in develop you may also use `field`s to execute statements.`field` is like `field_view`, but it owns strings and blobs. So something like

```
vector<field> params;
results result;
conn.execute(stmt.bind(params.begin(), params.end()), result);
```

Will work.

Note that develop is not as stable as official releases, though.

Regards,
Ruben.
