### ISSUE TITLE
execute is missing

### ISSUE THREAD

**Issue by Mecanik** [boostorg/mysql#160]
I`m using Boost 1.82 with the included MySQL, however the .execute() function is missing which is specified in the docs. Are the docs outdated or the code? Thanks.

**Comment by anarthal** [comment]
Actually the docs are too new - `execute()` is a newer, more general function that will be available in 1.83. execute() is in master but not in 1.82.

Docs for 1.82 are here: https://www.boost.org/doc/libs/1_82_0/libs/mysql/doc/html/index.html

You can achieve the same functionality in 1.82 using `connection::query` and `connection::execute_statement`.
