### ISSUE TITLE
close_statement makes the immediately subsequent operation slow

### ISSUE THREAD

**Issue by anarthal** [boostorg/mysql#181]
* When running a close statement op, the immediately subsequent operation takes a big amount of time (~40ms).
* This is due to the fact that close statement doesn't send any response back. We wait until the server sends a TCP-level ACK, which happens ~40ms later.
* The official C API doesn't suffer this. From my tests, it looks like they don't wait for the entire packet to be written before writing the next one. From Asio's API, doing this reliable doesn't look viable.
* A possible solution is to send a pipelined COM_PING packet with the close statement request. Ping is very lightweight and forces the server to write an OK packet.
* Tested with the async API `async_close_statement`, but very much likely affects the sync API, too.
* Tested under Ubuntu 22.04 (Linux 6.2.0).

**Comment by sheldonlyr** [comment]
How can we avoid this performance issue on application level? Any suggestions?

**Comment by sheldonlyr** [comment]
Hi! Thanks for so quick answer！

**Comment by sheldonlyr** [comment]
Oh, one more question😅 Does connection pool can be used in Boost 1.84? I'm really looking forward to the addition of this feature.

**Comment by anarthal** [comment]
I'm afraid it will be 1.85. I'm currently finishing docs and tests for the feature, so it can't make the times required by Boost for 1.84. I expect it to be in master in a few weeks though, and I'd be more than happy to have some early feedback.
