### ISSUE TITLE
Test libraries and executables should be declared EXCLUDE_FROM_ALL

### ISSUE THREAD

**Issue by pdimov** [boostorg/mysql#261]
The Boost convention is that `cmake --build .` only builds the libraries. Test libraries and executables are built with `cmake --build . --target tests`.

**Comment by anarthal** [comment]
Even if `BUILD_TESTING` is set?

**Comment by pdimov** [comment]
That's the only case it matters, as otherwise they aren't there at all.

**Comment by anarthal** [comment]
I'll change it. But what's the rationale? Not having to reconfigure with `BUILD_TESTING=OFF` if you don't want to build the tests?

**Comment by pdimov** [comment]
Pretty much, yes.

In the future, we should probably support separate build targets for a particular library's tests, too.
