### ISSUE TITLE
Floating point exception (core dumped)  

### ISSUE THREAD

**Issue by ezluo** [boostorg/mysql#295]
Execute the Update statement using connection_pool and receive the result. If the update is not successful (with correct statements), the unoptimized compiled GDB will debug and execute the next section of code, and the program will terminate abnormally（
Floating point exception (core dumped)
[1] + Floating point exception (core dumped) "/usr/bin/gdb"
）. 
Successfully updated or not debugged, the program is running normally.
﻿
system:ubuntu 2404

**Comment by anarthal** [comment]
Hi @ezluo,

Could you please provide a little bit more context so I can investigate?
- Which update statement are you running?
- Are you using text queries or prepared statements?

Thanks,
Ruben.

**Comment by ezluo** [comment]
I use the prepared statements

UPDATE ehsta SET `ta03`=1 WHERE ta01=?

TA03 is of the bit type

**Comment by ezluo** [comment]
There is also an abnormal ending when the preparation quote is not used

**Comment by anarthal** [comment]
What type is `ta1`? How does your `execute` / `bind` code look like?

> There is also an abnormal ending when the preparation quote is not used

I'm afraid I'm not following you here. Could you please paste a code sample oh what you mean?

Thanks,
Ruben.

**Comment by ezluo** [comment]
This error occurs without using the preparation statement
co_await conn->async_execute(
                sql, result, diag, tuple_awaitable);
            ec = std::get<0>(res);
            make_runtime_error();
This paragraph encapsulates a function,
After the function ends, call
if (! result.empty() && result.affected_rows() == 1)
esle
An exception occurred here

**Comment by ezluo** [comment]
The same exception occurs with or without SQL prepared statements.
The same exception occurs when a result check is not performed or when a result check is not performed

The type of Ta01 is a string

**Comment by ezluo** [comment]
This issue can be closed,
Attempted to debug using lldb, executed normally, and the dump file also showed as gdb exception.

**Comment by anarthal** [comment]
Was it a gdb bug? Closing as suggested.
