### ISSUE TITLE
Example: reconnect

### ISSUE THREAD

**Issue by anarthal** [boostorg/mysql#92]
Provide an example on how to reconnect a failed MySQL connection (e.g. due to a network failure).

**Comment by Mecanik** [comment]
Where is this example? Thanks a lot.

**Comment by anarthal** [comment]
I'm afraid this hasn't been done yet. There is a section on reconnection in the docs that explains the basics, which you may find useful: https://anarthal.github.io/mysql/mysql/reconnecting.html.

If you encounter any problem, please feel free to contact me for help.

Regards,
Ruben.

**Comment by anarthal** [comment]
`connection_pool` already does this out-of-the-box, and with `any_connection`, this should be trivial. I don't think we need this anymore.
