### ISSUE TITLE
OpenSSL dependency necessary?

### ISSUE THREAD

**Issue by 3n16m4** [boostorg/mysql#99]
First of all: Great library! Like really, really great. The interface is almost as if the library has already been in boost for several years and everything makes sense without digging too much into the documentation. I hope it makes it through the proposal process :)

I have one concern on the requirements for the use of this library though: Is the dependency OpenSSL really necessary? In my case, I'm running a local docker container with a MySQL server that I use without SSL but I still require to link it with OpenSSL and provide its headers. Forgive my ignorance but couldn't this be solved with macros to avoid compiling SSL based code when no OpenSSL was found? Right now it's not a problem, just inconvenient as I'm never planning to use OpenSSL 😅

Thanks!

**Comment by anarthal** [comment]
Hi, thanks.

OpenSSL is used for hashing passwords during the authentication phase (invoked by `connection::connect`), even if you are not using SSL/TLS enabled connections.

Regards,
Ruben.

**Comment by serfcity** [comment]
This functionality can be in #ifdef SSL_REQUIREMENT ... #else Boost.Mysql realization of this crypto function #endif

**Comment by anarthal** [comment]
The MySQL protocol mandates that all passwords must be sent hashed, even if you're not using encrypted connections. OpenSSL is used by `connection::handshake` and `connection::connect` to perform such hashing, even if using non-encrypted connections.

Even if SSL-related functionality was if-def'ed out, OpenSSL would still be required.

**Comment by serfcity** [comment]
How does MySQL++ and MySQL C API work then?
They do not require OpenSSL.

**Comment by anarthal** [comment]
The MySQL C API uses OpenSSL internally:

```
$ ldd /usr/lib/x86_64-linux-gnu/libmysqlclient.so.21.2.34
        linux-vdso.so.1 (0x00007fff5cba6000)
        libssl.so.3 => /lib/x86_64-linux-gnu/libssl.so.3 (0x00007fa51095c000)
        libcrypto.so.3 => /lib/x86_64-linux-gnu/libcrypto.so.3 (0x00007fa510400000)
        libresolv.so.2 => /lib/x86_64-linux-gnu/libresolv.so.2 (0x00007fa511111000)
        libzstd.so.1 => /lib/x86_64-linux-gnu/libzstd.so.1 (0x00007fa51088d000)
        libstdc++.so.6 => /lib/x86_64-linux-gnu/libstdc++.so.6 (0x00007fa510000000)
        libgcc_s.so.1 => /lib/x86_64-linux-gnu/libgcc_s.so.1 (0x00007fa5110ef000)
        libc.so.6 => /lib/x86_64-linux-gnu/libc.so.6 (0x00007fa50fc00000)
        /lib64/ld-linux-x86-64.so.2 (0x00007fa511143000)
        libm.so.6 => /lib/x86_64-linux-gnu/libm.so.6 (0x00007fa510319000)
```

As libmysqlclient is a compiled library, you only need the binary, not the headers. Boost.MySQL is header-only, and thus requires the headers, too. mysqlpp is a wrapper around libmysqlclient, so the same applies.

**Comment by serfcity** [comment]
Ok, and how to recompile boost.mysql with LibreSSL or GNUTLS?

**Comment by serfcity** [comment]
OpenSSL have a lot of security bugs: https://www.openssl.org/news/vulnerabilities.html
SHA256 really easy algorithm: http://www.zedwood.com/article/cpp-sha256-function

**Comment by anarthal** [comment]
If you've found a day-zero vuln on OpenSSL let me know ;)

From what I know, LibreSSL is API compatible with OpenSSL, so change your `find_package(OpenSSL REQUIRED)` for whatever LibreSSL offers and link against it.

**Comment by serfcity** [comment]
First of all СVEs were discovered before they were fixed by OpenSSL developers.
Also why I should link (and distribute and so on) OpenSSL library, if I don't use it?
Is 30 string of SHA256 implementation impossible requirement for boost.mysql?

**Comment by anarthal** [comment]
It's not a 30 string implementation, it's a bunch of testing, several CI builds to verify eveything works without OpenSSL, and a big refactor on how to detect / type erase SSL streams without pulling any `asio/ssl`  OpenSSL headers. It's not impossible, but it's not small at all.

**Comment by serfcity** [comment]
If I remember correctly, only 1 function was not link without -lssl. This is the reason to keep using MySQL++ instead of Boost.MySQL. And how Boost.MySQL work with Boost.asio with other crypto library: https://github.com/boostorg/asio/blob/28ff1e7c2b44f141eb809abaf2d76c95f38350ca/include/boost/asio/ssl/detail/openssl_types.hpp#L20 ?

**Comment by anarthal** [comment]
Are you currently using MySQL++ successfully? What's your motivation to move to Boost.MySQL?

**Comment by serfcity** [comment]
> Are you currently using MySQL++ successfully?
Yes, of course.
> What's your motivation to move to Boost.MySQL?
Because I use other Boost libraries in my project. That's united "eco-system" of Boost :-)
